blocks/breadcrumbs/breadcrumbs.css
blocks/hero/hero.css
styles/styles.css

Test URLs:
- After: https://mobile-fixes--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

mobile fixes

---

styles/styles.css

Fix #41
Test URLs:
- After: https://41-a11y-color-contrast--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

a11y heading color contrast

---

robots.txt

Test URLs:
- After: https://stage-robots--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

stage robots

---

blocks/fragment/fragment.js
scripts/scripts.js
styles/styles.css

Test URLs:
- After: https://fragment-fixes--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

Fragment fixes

---

blocks/columns/columns.css
styles/styles.css

Fix #47 
Test URLs:
- Before: https://main--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia/fundacion-railes-madrid
- After: https://subpage-styling--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia/fundacion-railes-madrid

Subpage styling

---

styles/styles.css

Test URLs:
- After: https://test-cdn--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

test change link color

---

styles/styles.css

Test URLs:
- After: https://test-cdn-revert--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

revert cdn test change

---

styles/styles.css

Test URLs:
- After: https://styling-9-18--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

style bug fixes

---

blocks/footer/footer.js

Test URLs:
- After: https://prod-footer-content--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

prod footr content

---

blocks/breadcrumbs/breadcrumbs.css

Test URLs:
- After: https://breadcrumbs-fix--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

breadcrumbs fix

---

blocks/footer/footer.css
styles/styles.css

Test URLs:
- After: https://a11y-fix-contrast--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

a11y contrast

---

blocks/footer/footer.css
blocks/footer/footer.js
scripts/lib-franklin.js
styles/styles.css

Test URLs:
- After: https://a11y-links--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

a11y links

---

styles/styles.css

Test URLs:
- After: https://highlight-section-full-width--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

highlight section full width

---

icons/palladium-care.svg

Test URLs:
- After: https://palladium-care-svg-color--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

palladium care svg color

---

helix-query.yaml

Test URLs:
- After: https://indexing-excludes--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

exclude fragments from indexing

---

icons/phone.svg

Test URLs:
- After: https://fix-header-icons--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

fix phone icon

---

blocks/header/header.js

Test URLs:
- After: https://prod-header--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

switch to /nav header content

---

styles/styles.css

Test URLs:
- After: https://a11y-reservas-link-color--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

a11y reservas link color

---

styles/styles.css

Test URLs:
- After: https://a11y-gold-dim--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

a11y gold dim

---

blocks/breadcrumbs/breadcrumbs.css
styles/styles.css

Test URLs:
- After: https://fixes-sept-25--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

sept 25 style fixes

---

styles/styles.css

Test URLs:
- After: https://home-bullets-flex--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

home bullets flex

---

hlx/blocks/header/header.css

Test URLs:
- After: https://logo-link--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

style icon logo

---

hlx/blocks/header/header.css

Test URLs:
- After: https://invalidation-test--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

invalidation test

---

hlx/blocks/header/header.css

Test URLs:
- After: https://invalidation-2--palladium--hlxsites.hlx.page/es/cares/4-causas/infancia

invalidation test 2
